name: e_commerce_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter_facebook_auth: ^7.1.5
  google_sign_in: ^7.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_carousel_widget: ^3.1.0
  flutter_dash: ^1.0.0
  flutter_native_splash: ^2.4.7
  persistent_bottom_nav_bar_v2: ^6.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png

flutter_native_splash:
  color: "#673AB7"
  color_dark: "#673AB7"
  image: assets/images/splash.png
  image_dark: assets/images/splash.png

  android_12:
    color: "#673AB7"
    color_dark: "#673AB7"
    image: assets/images/splash.png
    image_dark: assets/images/splash.png
    icon_background_color: "#673AB7"
